name: CI/CD for Portfolio

on:
  #push:
    #branches:
    # - main  # Trigger on push to main branch
  workflow_dispatch: #for not triggering to push

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Deploy to GitHub Pages
        id: gh-pages-deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./  # Assuming your build output is at the root level

      - name: Get Deployment URL
        id: get-url
        run: echo "::set-output name=url::https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"

      - name: Output Deployment URL
        run: echo "Deployed to ${{ steps.get-url.outputs.url }}"
